### ISSUE TITLE
Call failed: Other("No TLS"), even when enabling all features

### ISSUE THREAD

**Issue by SamuelMarks** [SergejJurecko/mio_httpc#16]
Kept debugging this up until the point where I had a `Cargo.toml` with:
```toml
[package]
name = "projectname"
version = "0.1.0"
authors = ["Samuel Marks @SamuelMarks"]
build = "build.rs" # your https://github.com/SergejJurecko/mio_httpc/blob/5e82852/build.rs
edition = "2018"

[dependencies]
mio = "0.6.16"
mio_httpc = "0.8.3"
crypto-hash = "0.3.1"
ring = "0.13.2"
webpki = "0.18.1"
webpki-roots = "0.15"
rustls = {version="0.14", features = ["dangerous_configuration"]}
openssl = { version = "0.10.*", features = ["v102", "v110"] }
native-tls = "0.2"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
core-foundation = "0.6"
core-foundation-sys = "0.6"
```

Yet whenever I run this function, it dies with the `No TLS` error:
```rust
pub fn download() {
    let poll = Poll::new().unwrap();
    let urls = vec!["https://github.com/SergejJurecko/mio_httpc"];

    let cfg = if let Ok(cfg) = HttpcCfg::certs_from_path(".") {
        cfg
    } else {
        Default::default()
    };
    let mut htp = Httpc::new(10, Some(cfg));

    for url in urls {
        println!("Get {}", url);
        let call = CallBuilder::get()
            .url(url)
            .expect("Invalid url")
            .timeout_ms(10000)
            .https() // also tried without this line
            .simple_call(&mut htp, &poll)
            .expect("Call start failed");
        do_call(&mut htp, &poll, call);

        println!("Open connections={}", htp.open_connections());
    }
}
```
